name: Generate profile stats cards

on:
  schedule:
    - cron: "0 4 * * *"   # once a day
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "profile-summary-card-output/**"

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
